config/routes.rb
Rails.application.routes.draw do
  root 'site/home#index'
  post '/rate' => 'rater#create', :as => 'rate'
  get 'backoffice', to: 'backoffice/dashboard#index'

  namespace :backoffice do
    resources :send_mail, only: [:edit, :create]
    resources :categories, except: [:show, :destroy]
    resources :admins, except: [:show]
    resources :diagrams, only: [:index]
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :site do
    get 'home', to: 'home#index'
    get 'search', to: 'search#ads'
    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, only: [:index, :edit, :update, :new, :create]
      resources :my_data, only: [:edit, :update]
    end

    resources :ad_detail, only: [:index, :show]
    resources :categories, only: [:show]
    resources :comments, only: [:create]
  end

  namespace :checkout do
    resources :payments, only: [:create]
    resources :notifications, only: [:create]
  end

  devise_for :admins, :skip => [:registrations]
  devise_for :members, controllers: {
    sessions: 'members/sessions',
    registrations: 'members/registrations'
  }

  namespace :api do
    scope '/v1' do
      get '/' => 'base_api#index'
      scope '/login' do
        post '/' => 'login#index'
      end
      scope '/category' do
        get '/get-all' => 'category#index'
        post '/get' => 'category#show'
        post '/create' => 'category#create'
        post '/update' => 'category#update'
        post '/delete' => 'category#destroy'
      end
      scope '/member' do
        get '/get-all' => 'member#index'
        post '/get' => 'member#show'
        post '/create' => 'member#create'
        post '/update' => 'member#update'
        post '/delete' => 'member#destroy'
      end
      scope '/comment' do
        get '/get-all' => 'comment#index'
        post '/get' => 'comment#show'
        post '/create' => 'comment#create'
        post '/update' => 'comment#update'
        post '/delete' => 'comment#destroy'
      end
      scope '/ad' do
        get '/get-all' => 'ad#index'
        post '/get' => 'ad#show'
        post '/create' => 'ad#create'
        post '/update' => 'ad#update'
        post '/delete' => 'ad#destroy'
      end
    end
  end
end

app/controllers/backoffice/admins_controller.rb
class Backoffice::AdminsController < BackofficeController
  before_action :set_admin, only: [:edit, :update, :destroy]
  after_action :verify_authorized, only: [:new, :destroy]
  after_action :verify_policy_scoped, only: :index

  def index
    @admins = policy_scope(Admin)
  end

  def new
    @admin = Admin.new
    authorize @admin
  end

  def create
    @admin = Admin.new(params_admin)
    if @admin.save
      redirect_to backoffice_admins_path, notice: "O adminstrador #{@admin.email} foi registrado!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    update_roles

    if @admin.update(params_admin)
      AdminMailer.update_email(current_admin, @admin).deliver_now
      redirect_to backoffice_admins_path, notice: "O adminstrador #{@admin.email} foi alterado!"
    else
      render :edit
    end
  end

  def destroy
    authorize @admin
    admin_email = @admin.email
    if @admin.destroy
      redirect_to backoffice_admins_path, notice: "O adminstrador #{admin_email} foi apagado!"
    else
      render :index
    end
  end

  private
    def remove_all_roles
      Role::ROLES.each do |role|
        @admin.remove_role(role)
      end
    end

    def update_roles
      remove_all_roles
      roles = params[:admin].extract!(:role_ids)
      roles[:role_ids].each do |role|
        @admin.add_role(role)
      end
    end

    def set_admin
      @admin = Admin.find(params[:id])
    end

    def params_admin
      if password_blank?
        params[:admin].except!(:password, :password_confirmation)
      end

      if @admin.blank?
        params.require(:admin).permit(:name, :email, :role, :password, :password_confirmation)
      else
        params.require(:admin).permit(policy(@admin).permitted_attributes)
      end
    end

    def password_blank?
      params[:admin][:password].blank? && params[:admin][:password_confirmation].blank?
    end
end

app/controllers/backoffice/categories_controller.rb
class Backoffice::CategoriesController < BackofficeController
  before_action :set_category, only: [:edit, :update]

  def index
    @categories = Category.all
  end

  def new
    @category = Category.new
  end

  def create
    @category = CategoryService.create(params_category)
    unless @category.errors.any?
      redirect_to backoffice_categories_path, notice: "Categoria #{@category.description} salva!"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update(params_category)
      redirect_to backoffice_categories_path, notice: "Categoria #{@category.description} atualizada!"
    else
      render :edit
    end
  end

  private
    def set_category
      @category = Category.friendly.find(params[:id])
    end

    def params_category
      params.require(:category).permit(:description)
    end
end

app/controllers/backoffice/categories_controller/category_service.rb
class Backoffice::CategoriesController::CategoryService
  attr_accessor :category

  def self.create(params_category)
    @category = Category.new(params_category)

    if @category.valid?
      @category.save!
    end

    @category
  end
end

app/controllers/backoffice/dashboard_controller.rb
class Backoffice::DashboardController < BackofficeController
  def index
    @categories_groups = Category.all.map {|c| [c.description, c.ads_count]}
  end
end

app/controllers/backoffice/diagrams_controller.rb
class Backoffice::DiagramsController < BackofficeController
  def index
    %x(bundle exec erd --filename='public/diagram')
  end
end

app/controllers/backoffice/send_mail_controller.rb
class Backoffice::SendMailController < ApplicationController
  def edit
    @admin = Admin.find(params[:id])

    respond_to do |format|
      format.js
    end
  end

  def create
    begin
      AdminMailer.send_message(current_admin, params[:'recipient-text'], params[:'subject-text'], params[:'message-text']).deliver_later
      @notify_message = 'Email enviado com sucesso!'
      @notify_flag = 'success'
    rescue
      @notify_message = 'Erro ao enviar email. Tente novamente'
      @notify_flag = 'error'
    end

    respond_to do |format|
      format.js
    end
  end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
  before_action :authenticate_admin!

  layout 'backoffice'


  def pundit_user
    current_admin
  end
end

app/helpers/backoffice/admins_helper.rb
module Backoffice::AdminsHelper
  RoleOption = Struct.new(:index, :description)

  def options_for_role
    Role::ROLES.map do |key, value|
      RoleOption.new(key, value)
    end
  end
end

app/helpers/backoffice/categories_helper.rb
module Backoffice::CategoriesHelper
end

app/helpers/backoffice/dashboard_helper.rb
module Backoffice::DashboardHelper
end

app/helpers/backoffice/diagrams_helper.rb
module Backoffice::DiagramsHelper
end

app/helpers/backoffice/send_mail_helper.rb
module Backoffice::SendMailHelper
end

app/views/backoffice/admins/edit.html.erb
<%= render partial: 'backoffice/admins/shared/form', locals: { action: 'Editando Admin' } %>

app/views/backoffice/admins/index.html.erb
<h1 class="page-header">Administradores</h1>
<div class="panel panel-default">
    <div class="panel-heading">
        Listando Administradores
        <% if policy(@admins).new? %>
          <%= link_to new_backoffice_admin_path, class: 'btn btn-success btn-circle pull-right', style: 'margin-top: -5px;' do %>
            <i class="fa fa-plus"></i>
          <% end %>
        <% end %>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Nome</th>
                        <th>Tipo de acesso</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    <% @admins.each do |admin| %>
                        <tr>
                            <td><%= admin.id %></td>
                            <td><%= admin.name %></td>
                            <td><%= admin.roles_descriptions.join(',') %></td>
                            <td style="width: 130px">
                                <%= link_to edit_backoffice_send_mail_path(admin.id), class: 'btn btn-info btn-circle', remote: true do %>
                                    <i class="fa fa-envelope"></i>
                                <% end %>
                                <%= link_to edit_backoffice_admin_path(admin), class: 'btn btn-primary btn-circle' do %>
                                    <i class="fa fa-edit"></i>
                                <% end %>
                                <% if current_admin.id != admin.id && policy(@admins).destroy?%>
                                    <%= link_to backoffice_admin_path(admin), method: :delete, class: 'btn btn-danger btn-circle', data: {confirm: t('messages.confirm_with', item: admin.name)} do %>
                                        <i class="fa fa-times"></i>
                                    <% end %>
                                <% else %>
                                    <%= link_to '#', class: 'btn btn-danger btn-circle', disabled: 'disabled' do %>
                                        <i class="fa fa-times"></i>
                                    <% end %>
                                <% end %>
                            </td>
                        </tr>
                    <% end %>
                </tbody>
            </table>
        </div>
        <!-- /.table-responsive -->
    </div>
            <!-- /.panel-body -->
</div>

<%= render partial: 'backoffice/admins/shared/send_email_modal' %>
    <!-- /.panel -->
<!-- /.col-lg-12 -->

app/views/backoffice/admins/new.html.erb
<%= render partial: 'backoffice/admins/shared/form', locals: { action: 'Criando Admin' } %>