config/routes.rb
Rails.application.routes.draw do
  root 'site/home#index'
  post '/rate' => 'rater#create', :as => 'rate'
  get 'backoffice', to: 'backoffice/dashboard#index'

  namespace :backoffice do
    resources :send_mail, only: [:edit, :create]
    resources :categories, except: [:show, :destroy]
    resources :admins, except: [:show]
    resources :diagrams, only: [:index]
    get 'dashboard', to: 'dashboard#index'
  end

  namespace :site do
    get 'home', to: 'home#index'
    get 'search', to: 'search#ads'
    namespace :profile do
      resources :dashboard, only: [:index]
      resources :ads, only: [:index, :edit, :update, :new, :create]
      resources :my_data, only: [:edit, :update]
    end

    resources :ad_detail, only: [:index, :show]
    resources :categories, only: [:show]
    resources :comments, only: [:create]
  end

  namespace :checkout do
    resources :payments, only: [:create]
    resources :notifications, only: [:create]
  end

  devise_for :admins, :skip => [:registrations]
  devise_for :members, controllers: {
    sessions: 'members/sessions',
    registrations: 'members/registrations'
  }

  namespace :api do
    scope '/v1' do
      get '/' => 'base_api#index'
      scope '/login' do
        post '/' => 'login#index'
      end
      scope '/category' do
        get '/get-all' => 'category#index'
        post '/get' => 'category#show'
        post '/create' => 'category#create'
        post '/update' => 'category#update'
        post '/delete' => 'category#destroy'
      end
      scope '/member' do
        get '/get-all' => 'member#index'
        post '/get' => 'member#show'
        post '/create' => 'member#create'
        post '/update' => 'member#update'
        post '/delete' => 'member#destroy'
      end
      scope '/comment' do
        get '/get-all' => 'comment#index'
        post '/get' => 'comment#show'
        post '/create' => 'comment#create'
        post '/update' => 'comment#update'
        post '/delete' => 'comment#destroy'
      end
      scope '/ad' do
        get '/get-all' => 'ad#index'
        post '/get' => 'ad#show'
        post '/create' => 'ad#create'
        post '/update' => 'ad#update'
        post '/delete' => 'ad#destroy'
      end
    end
  end
end

app/views/backoffice/admins/shared/_form.html.erb
<h1 class="page-header">Administradores</h1>
<% if @admin.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <ul>
            <% @admin.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
        </ul>
    </div>
<% end %>
<div class="panel panel-default">
    <div class="panel-heading">
        <%= action %>
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">
        <div class="col-lg-6">
            <%= form_for([:backoffice, @admin]) do |f| %>
                <div class="form-group">
                    <label>Nome</label>
                    <%= f.text_field :name, class: 'form-control', placeholder: 'Nome do admin'%>
                </div>
                <div class="form-group">
                    <label>Email</label>
                    <%= f.text_field :email, class: 'form-control', placeholder: 'Email do admin'%>
                </div>
                <% if policy(@admin).edit? %>
                    <div class="form-group">
                        <%= f.label :role %>
                        <%= f.collection_check_boxes :role_ids, options_for_role, :index, :description, checked: @admin.checked_roles do |b| %>
                            <div class="radio">
                                <%= b.label { b.check_box + b.text } %>
                            </div>
                        <% end %>
                    </div>
                <% end %>
                <div class="form-group">
                    <label>Senha</label>
                    <%= f.password_field :password, class: 'form-control', placeholder: 'Senha'%>
                </div>

                <div class="form-group">
                    <label>Confirmação da Senha</label>
                    <%= f.password_field :password_confirmation, class: 'form-control', placeholder: 'Confirmação da Senha'%>
                </div>
                <button type="submit" class="btn btn-default">Salvar</button>
            <% end%>
        </div>
    </div>
            <!-- /.panel-body -->
</div>
    <!-- /.panel -->

app/views/backoffice/admins/shared/_send_email.html.erb
<div class="modal fade" id="sendMailModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">New message</h4>
      </div>
      <div class="modal-body">
        <%= form_tag(backoffice_send_mail_index_path, remote: true) do %>
          <div class="form-group">
            <label for="recipient-name" class="control-label">Recipient:</label>
            <%= text_field_tag(:'recipient-text', nil, class: 'form-control', readonly: 'readonly') %>
          </div>
          <div class="form-group">
            <label for="recipient-name" class="control-label">Subject:</label>
            <%= text_field_tag(:'subject-text', nil, class: 'form-control') %>
          </div>
          <div class="form-group">
            <label for="message-text" class="control-label">Message:</label>
            <%= text_area_tag(:'message-text', nil, class: 'form-control') %>
          </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= submit_tag 'Send message', class: 'btn btn-primary' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/backoffice/admins/shared/_send_email_modal.html.erb
<div class="modal fade" id="sendMailModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">New message</h4>
      </div>
      <div class="modal-body">
        <%= form_tag(backoffice_send_mail_index_path, remote: true) do %>
          <div class="form-group">
            <label for="recipient-text" class="control-label">Recipient:</label>
            <%= text_field_tag(:'recipient-text', nil, class: 'form-control', readonly: 'readonly') %>
          </div>
          <div class="form-group">
            <label for="recipient-text" class="control-label">Subject:</label>
            <%= text_field_tag(:'subject-text', nil, class: 'form-control', required: 'required') %>
          </div>
          <div class="form-group">
            <label for="message-text" class="control-label">Message:</label>
            <%= text_area_tag(:'message-text', nil, class: 'form-control') %>
          </div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= submit_tag 'Send message', class: 'btn btn-primary' %>
      </div>
      <% end %>
    </div>
  </div>
</div>